name: basmalah
description: aplikasi setting jadwal sholat

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^1.9.5
  flutter_bluetooth_serial: ^0.2.2
  scoped_model: ^1.0.1
  cupertino_icons: ^1.0.2
  random_color_scheme: ^0.1.3
  awesome_dialog: ^1.3.2
  grafpix: ^1.2.8
  shared_preferences: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
